#!/bin/bash

#License:
#"Remote Syslog" is a free application what can be used to view syslog messages.
#Copyright (C) 2021 Tom Slenter
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#For more information contact the author:
#Name author: Tom Slenter
#E-mail: info@remotesyslog.com

#Banner
function banner() {
    echo ""
    echo "##################################################"
    echo "#Remote Syslog Elasticsearch Viewer              #"
    echo "#More information: https://www.remotesyslog.com  #"
    echo "#Remote Syslog viewer for Elasticsearch          #"
    echo "#Version: RSEVIEW 0.3                            #"
    echo "#URL: https://github.com/tslenter/rseview        #"
    echo "#Donation: https://github.com/tslenter/RS        #"
    echo "##################################################"
    echo ""
}
banner
